CREATE TABLE IF NOT EXISTS profile (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  headline TEXT NOT NULL,
  location TEXT NOT NULL,
  summary TEXT NOT NULL,
  email TEXT NOT NULL,
  linkedin TEXT NOT NULL,
  github TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS skills (
  id SERIAL PRIMARY KEY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  level TEXT NOT NULL DEFAULT 'Learning',
  sort_order INTEGER NOT NULL DEFAULT 100,
  UNIQUE(category, name)
);

CREATE TABLE IF NOT EXISTS experience (
  id SERIAL PRIMARY KEY,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  period TEXT NOT NULL,
  location TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS experience_bullets (
  id SERIAL PRIMARY KEY,
  experience_id INTEGER NOT NULL REFERENCES experience(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS certifications (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL DEFAULT 100
);
